/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IConsumer,
  IConsumerInterface,
} from "../../../contracts/protocol/IConsumer";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_stonkslyRequestId",
        type: "uint256",
      },
      {
        internalType: "string[]",
        name: "args",
        type: "string[]",
      },
    ],
    name: "init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IConsumer__factory {
  static readonly abi = _abi;
  static createInterface(): IConsumerInterface {
    return new utils.Interface(_abi) as IConsumerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IConsumer {
    return new Contract(address, _abi, signerOrProvider) as IConsumer;
  }
}
