/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Consumer__factory } from "./Consumer__factory";
export { IConsumer__factory } from "./IConsumer__factory";
export { IStonksly__factory } from "./IStonksly__factory";
export { PurchaseConsumer__factory } from "./PurchaseConsumer__factory";
export { SToken__factory } from "./SToken__factory";
export { STokenManager__factory } from "./STokenManager__factory";
export { SaleConsumer__factory } from "./SaleConsumer__factory";
export { Stonksly__factory } from "./Stonksly__factory";
