/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Consumer } from "./Consumer";
export type { IConsumer } from "./IConsumer";
export type { IStonksly } from "./IStonksly";
export type { PurchaseConsumer } from "./PurchaseConsumer";
export type { SToken } from "./SToken";
export type { STokenManager } from "./STokenManager";
export type { SaleConsumer } from "./SaleConsumer";
export type { Stonksly } from "./Stonksly";
export type { StonkslyToken } from "./StonkslyToken";
